services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing-app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: listmonk_listmonk
